import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { verifyContractBinding } from "../scripts/verify-contract.mjs";

const LOCAL_CANDIDATE_VERSION = "3.0.0-web-snapshot";

test("the snapshot is bound to the declared current API local candidate", async () => {
  const report = await verifyContractBinding();

  assert.deepEqual(report.problems, []);
  assert.equal(report.descriptor.schemaVersion, 1);
  assert.equal(report.descriptor.sourceRepository, "monorepo");
  assert.equal(report.descriptor.sourceState, "LOCAL_UNCOMMITTED_CANDIDATE");
  assert.equal(report.descriptor.sourcePath, "docs/backend-contracts/openapi.yaml");
  assert.equal(report.descriptor.contractVersion, LOCAL_CANDIDATE_VERSION);
  assert.equal(report.declaredVersion, report.descriptor.contractVersion);
  assert.equal(report.sha256, report.descriptor.sha256);
  assert.match(report.descriptor.sha256, /^[a-f0-9]{64}$/);
  assert.equal(report.byteLength, report.descriptor.byteLength);
  assert.equal(report.counts.operations, report.descriptor.operationCount);
  assert.equal(report.counts.schemas, report.descriptor.schemaCount);
  assert.ok(report.counts.paths > 0);
  assert.match(report.descriptor.sourceCommit, /^[a-f0-9]{40}$/);
});

test("the generated types are the ones openapi-typescript emits for that snapshot", async () => {
  // `npm run contract:check` regenerates and diffs; this guards the cheap
  // giveaway that the file was hand-edited or left behind by an older sync.
  const generated = await readFile(
    new URL("../app/openapi.generated.ts", import.meta.url),
    "utf8",
  );

  assert.match(generated, /This file was auto-generated by openapi-typescript/);
  assert.match(
    generated,
    /Submit a draft and atomically create a system VALID ReviewRecord/,
  );
  assert.match(
    generated,
    /Append a VALID or INVALID correction to the current two-state review/,
  );
});

test("the client never re-derives a review state the Backend owns", async () => {
  const teacherData = await readFile(
    new URL("../app/teacher-data.ts", import.meta.url),
    "utf8",
  );

  // Every audit state must be read from the server's currentReview projection.
  assert.match(teacherData, /const result = record\.currentReview\?\.result;/);
  assert.match(teacherData, /if \(result === "VALID"\) return "valid";/);
  assert.match(teacherData, /if \(result === "INVALID"\) return "invalid";/);
  assert.doesNotMatch(teacherData, /attempt-context|ExerciseRecordAttemptContext/);
});
